name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.4'

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build .

    - name: Test With Coverage
      run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Run Vet & Lint
      run: |
        go vet ./...
        golint -set_exit_status=1 ./...


